name: menu_restaux
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  #UI
  cupertino_icons: ^1.0.5
  responsive_framework: ^0.2.0
  getwidget: ^3.1.1
  font_awesome_flutter: ^10.4.0
  sidebarx: ^0.16.0
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4
  intl: ^0.18.1
  image_picker: ^1.0.1





  #LOGIC
  flutter_bloc: ^8.1.3


  #Api
  url_launcher: ^6.1.11
  #Navigation
  go_router: ^8.2.0
  #LocalStorage
  get_storage: ^2.1.1
  http: ^1.1.0
  uuid: ^3.0.7
 





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.2

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svg/




  # fonts:
  #   - family: NunitoSans
  #     fonts:
  #       - asset: assets/fonts/NunitoSans-VariableFont.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
